#!/bin/sh
set -e
# Automatically added by dh_icons/13.15.3
if command -v update-icon-caches >/dev/null; then
	update-icon-caches /usr/share/icons/Windows-10-Icons
fi
# End automatically added section
