#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p sr-undercover /usr/share/sr-undercover
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p sr-undercover /usr/share/sr-undercover || true
fi

# End automatically added section
# Automatically added by dh_icons/13.15.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if command -v update-icon-caches >/dev/null; then
		update-icon-caches /usr/share/icons/Windows-10-Icons
	fi
fi
# End automatically added section
